### ISSUE TITLE
Integrating makes AppImageLauncher crash after it moved the file, before launching

### ISSUE THREAD

**Issue by zilti** [TheAssassin/AppImageLauncher#250]
I customized the target directory for moving the AppImage files. When I click an AppImage, and select to integrate, it successfully moves the file and creates the launcher entry, but then crashes before launching it.
My system is OpenSUSE Leap 15.1.
Here's the dump from the KDE crash wizard:
```
Application: AppImageLauncher (AppImageLauncher), signal: Aborted
Using host libthread_db library "/lib64/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f9e598cd640 (LWP 20475))]

Thread 4 (Thread 0x7f9e316e3700 (LWP 20489)):
#0  0x00007f9e57a448ad in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007f9e323ee92b in  () at /usr/lib64/dri/i965_dri.so
#2  0x00007f9e323ee637 in  () at /usr/lib64/dri/i965_dri.so
#3  0x00007f9e57a3e569 in start_thread () at /lib64/libpthread.so.0
#4  0x00007f9e56a7a9ef in clone () at /lib64/libc.so.6

Thread 3 (Thread 0x7f9e39fb2700 (LWP 20478)):
#0  0x00007f9e57a47eb8 in read () at /lib64/libpthread.so.0
#1  0x00007f9e59478ca0 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f9e59433cb8 in g_main_context_check () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f9e59434150 in  () at /usr/lib64/libglib-2.0.so.0
#4  0x00007f9e594342bc in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#5  0x00007f9e575cd96b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#6  0x00007f9e5757290a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#7  0x00007f9e57390daa in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#8  0x00007f9e591719e5 in  () at /usr/lib64/libQt5DBus.so.5
#9  0x00007f9e57395ced in  () at /usr/lib64/libQt5Core.so.5
#10 0x00007f9e57a3e569 in start_thread () at /lib64/libpthread.so.0
#11 0x00007f9e56a7a9ef in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7f9e47b5b700 (LWP 20477)):
#0  0x00007f9e56a7019b in poll () at /lib64/libc.so.6
#1  0x00007f9e4fe4a307 in  () at /usr/lib64/libxcb.so.1
#2  0x00007f9e4fe4bf3a in xcb_wait_for_event () at /usr/lib64/libxcb.so.1
#3  0x00007f9e49e73939 in  () at /usr/lib64/libQt5XcbQpa.so.5
#4  0x00007f9e57395ced in  () at /usr/lib64/libQt5Core.so.5
#5  0x00007f9e57a3e569 in start_thread () at /lib64/libpthread.so.0
#6  0x00007f9e56a7a9ef in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7f9e598cd640 (LWP 20475)):
[KCrash Handler]
#6  0x00007f9e569b8160 in raise () at /lib64/libc.so.6
#7  0x00007f9e569b9741 in abort () at /lib64/libc.so.6
#8  0x00007f9e569fb4a7 in __libc_message () at /lib64/libc.so.6
#9  0x00007f9e56a01cc3 in malloc_printerr () at /lib64/libc.so.6
#10 0x00007f9e56a035c9 in _int_free () at /lib64/libc.so.6
#11 0x00007f9e54d5653a in  () at /usr/lib64/libcairo.so.2
#12 0x00007f9e54d56ae5 in cairo_image_surface_create_from_png_stream () at /usr/lib64/libcairo.so.2
#13 0x00007f9e57c96a19 in appimage::utils::IconHandleCairoRsvg::tryLoadPng(std::vector<char, std::allocator<char> > const&) (this=0x26c3a90, data=...) at /ws/lib/libappimage/src/libappimage/utils/IconHandleCairoRsvg.cpp:129
#14 0x00007f9e57c975b5 in appimage::utils::IconHandleCairoRsvg::IconHandleCairoRsvg(std::vector<char, std::allocator<char> > const&) (this=0x26c3a90, data=...) at /ws/lib/libappimage/src/libappimage/utils/IconHandleCairoRsvg.cpp:56
#15 0x00007f9e57c90940 in appimage::utils::IconHandle::Priv::Priv(std::vector<char, std::allocator<char> > const&) (data=std::vector of length 38841042, capacity 38842936 = {...}, this=0x26c3a90) at /ws/lib/libappimage/src/libappimage/utils/IconHandle.cpp:23
#16 0x00007f9e57c90940 in appimage::utils::IconHandle::IconHandle(std::vector<char, std::allocator<char> >&) (this=0x7ffcd4c1ca80, data=std::vector of length 38841042, capacity 38842936 = {...}) at /ws/lib/libappimage/src/libappimage/utils/IconHandle.cpp:31
#17 0x00007f9e57ca6045 in appimage::desktop_integration::Thumbnailer::generateNormalSizeThumbnail(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<char, std::allocator<char> >&) const (this=this@entry=0x277e960, canonicalPathMd5="cb552cf735bf3ece60e9463a2478be30", normalIconData=std::vector of length 38841042, capacity 38842936 = {...}) at /ws/lib/libappimage/src/libappimage/desktop_integration/Thumbnailer.cpp:73
#18 0x00007f9e57ca6d8c in appimage::desktop_integration::Thumbnailer::create(appimage::core::AppImage const&) (this=0x277e960, appImage=...) at /ws/lib/libappimage/src/libappimage/desktop_integration/Thumbnailer.cpp:49
#19 0x00007f9e57c97dfd in appimage::desktop_integration::IntegrationManager::generateThumbnails(appimage::core::AppImage const&) const (this=this@entry=0x7ffcd4c1d050, appImage=...) at /ws/lib/libappimage/src/libappimage/desktop_integration/IntegrationManager.cpp:140
#20 0x00007f9e57c86a36 in appimage_register_in_system(char const*, bool) (path=<optimized out>, verbose=<optimized out>) at /ws/lib/libappimage/src/libappimage/libappimage.cpp:279
#21 0x000000000041af08 in installDesktopFileAndIcons(QString const&, bool) ()
#22 0x000000000041daf6 in integrateAppImage(QString const&, QString const&) ()
#23 0x000000000040ba9b in main::{lambda()#2}::operator()() const ()
#24 0x000000000040d94b in main ()
[Inferior 1 (process 20475) detached]

```

**Comment by TheAssassin** [comment]
Missing information on the version of AppImageLauncher involved and what AppImage this fails on.

**Comment by zilti** [comment]
The version form today, and every AppImage. At least both I tried. One of them being this one: https://github.com/zilti/riot-web.AppImage/releases/download/continuous/Riot-x86_64.AppImage

**Comment by TheAssassin** [comment]
> The version form today,

There's been at least 5 versions today. You need to be more precise. Also, I wonder how you installed AppImageLauncher.

I've tested the scenario you describe earlier today. I haven't seen any issues so far. The issue seems to be in your version of libcairo/librsvg.

**Comment by TheAssassin** [comment]
Seems to work in a Leap VM (GNOME edition, user interface is a bit broken there...). Have you tried moving the files back? Does that still work?

**Comment by TheAssassin** [comment]
@zilti any news? I'll have to close the issue as not reproducible.

**Comment by zilti** [comment]
It does work now.
