### ISSUE TITLE
Lite version constantly crashes

### ISSUE THREAD

**Issue by bam80** [TheAssassin/AppImageLauncher#333]
The service crashes in loop:
```
May 19 23:53:55 host systemd[355152]: appimagelauncherd.service: Main process exited, code=dumped, status=11/SEGV
May 19 23:53:55 host systemd[355152]: appimagelauncherd.service: Failed with result 'core-dump'.
May 19 23:53:55 host systemd-coredump[360843]: Process 360797 (appimagelaunche) of user 1001 dumped core.
                                               
                                               Stack trace of thread 360797:
                                               #0  0x00007f3a1ae9fa2c n/a (n/a)
May 19 23:54:05 host systemd[355152]: appimagelauncherd.service: Scheduled restart job, restart counter is at 72.
May 19 23:54:05 host systemd[355152]: Stopped AppImageLauncher daemon.
May 19 23:54:05 host systemd[355152]: Started AppImageLauncher daemon.
May 19 23:54:06 host appimagelauncher-lite.AppImage[360857]: Searching for existing AppImages
May 19 23:54:06 host appimagelauncher-lite.AppImage[360857]: Searching directory: /home/bam/Applications
May 19 23:54:06 host appimagelauncher-lite.AppImage[360857]: Found AppImage: /home/bam/Applications/Sourcetrail_2020_1_117_Li>
May 19 23:54:06 host appimagelauncher-lite.AppImage[360857]: AppImage integrated already, skipping
May 19 23:54:06 host appimagelauncher-lite.AppImage[360857]: Searching directory: /var/home/bam
May 19 23:54:06 host appimagelauncher-lite.AppImage[360857]: Watching directories: /home/bam/Applications /var/home/bam
May 19 23:54:38 host systemd[355152]: appimagelauncherd.service: Main process exited, code=dumped, status=11/SEGV
```
**System, software and AppImage information**
`appimagelauncher-lite-2.1.3-travis975-7408819-x86_64.AppImage`
Fedora 31

**Comment by ABotelho23** [comment]
`May 30 12:40:46 alexDeskLin systemd[2014]: appimagelauncherd.service: Main process exited, code=dumped, status=11/SEGV
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit UNIT has exited.
-- 
-- The process' exit code is 'dumped' and its exit status is 11.
May 30 12:40:46 alexDeskLin systemd[2014]: appimagelauncherd.service: Failed with result 'core-dump'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit UNIT has entered the 'failed' state with result 'core-dump'.
`
Also getting the error with non-lite. I will sometimes also get the Gnome crash dialog. Using Ubuntu 20.04.

**Comment by TheAssassin** [comment]
Could not reproduce these errors in any way. If you can get hands on such a core dump, please upload them along with the packaged binaries here on GitHub.

**Comment by thibaultmol** [comment]
Not sure how related. But regular appimagelauncher (from the arch repo's) is crashing every 40 seconds or something. Coredumping every time

https://drive.google.com/file/d/1jYO4nfx2zFMsLqYZAHaDajf9JHvkNfJC/view?usp=sharing

<details>
  <summary>System specs</summary>
  Operating System: Manjaro Linux
KDE Plasma Version: 5.21.1
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2
Kernel Version: 5.10.18-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: GeForce GTX 1080/PCIe/SSE2
</details>

**Comment by bam80** [comment]
This problem still happens to me.
Any way to say systemd stop restarting the service if it was failed several times in a row?

**Comment by trinitronx** [comment]
> Could not reproduce these errors in any way. If you can get hands on such a core dump, please upload them along with the packaged binaries here on GitHub.


@TheAssassin: Here's a recent coredump + bundled files from the [`extra/appimagelauncher` Manjaro Linux package][1][^1] version `2.2.0-10`:

[appimagelauncherd-183918-2024-09-13.core.dump-bundle.tar.gz](https://github.com/user-attachments/files/17002766/appimagelauncherd-183918-2024-09-13.core.dump-bundle.tar.gz)

```console
$ gdb  /usr/bin/appimagelauncherd  -c /tmp/appimagelauncherd-183918-2024-09-13.core.dump

GNU gdb (GDB) 15.1
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/appimagelauncherd...
(No debugging symbols found in /usr/bin/appimagelauncherd)
[New LWP 183918]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/usr/bin/appimagelauncherd'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  std::local_Rb_tree_increment (__x=0x5962486dad10) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++98/tree.cc:71

warning: 71	/usr/src/debug/gcc/gcc/libstdc++-v3/src/c++98/tree.cc: No such file or directory
(gdb) bt
#0  std::local_Rb_tree_increment (__x=0x5962486dad10) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++98/tree.cc:71
#1  std::local_Rb_tree_increment (__x=0x5962486dad10) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++98/tree.cc:60
#2  std::_Rb_tree_increment (__x=0x5962486dad10) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++98/tree.cc:85
#3  0x0000596233ebf909 in ??? ()
#4  0x0000596233ebade7 in ??? ()
#5  0x0000793c2e6e35de in ??? () at /usr/lib/libQt5Core.so.5
#6  0x0000793c2e6e563e in QTimer::timeout(QTimer::QPrivateSignal) () at /usr/lib/libQt5Core.so.5
#7  0x0000793c2e6d5529 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#8  0x0000793c2e6aeea7 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#9  0x0000793c2e6fd8b0 in QTimerInfoList::activateTimers() () at /usr/lib/libQt5Core.so.5
#10 0x0000793c2e6fe032 in ??? () at /usr/lib/libQt5Core.so.5
#11 0x0000793c2eaa1299 in ??? () at /usr/lib/libglib-2.0.so.0
#12 0x0000793c2eb03ec7 in ??? () at /usr/lib/libglib-2.0.so.0
#13 0x0000793c2eaa0795 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#14 0x0000793c2e6fe1af in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#15 0x0000793c2e6a6b9c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#16 0x0000793c2e6b309d in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#17 0x0000596233eb3c15 in ??? ()
#18 0x0000793c2de34e08 in ??? () at /usr/lib/libc.so.6
#19 0x0000793c2de34ecc in __libc_start_main () at /usr/lib/libc.so.6
#20 0x0000596233eb45b5 in ??? ()
```

[^1]: [pkg signature][2]

[1]: https://mirrors.manjaro.org/repo/unstable/extra/x86_64/appimagelauncher-2.2.0-10-x86_64.pkg.tar.zst
[2]: https://mirrors.manjaro.org/repo/unstable/extra/x86_64/appimagelauncher-2.2.0-10-x86_64.pkg.tar.zst.sig

**Comment by TheAssassin** [comment]
Cannot be reproduced in 3.0.0 any more. Considered fixed.
