### ISSUE TITLE
"Failed to register AppImage in system via libappimage"

### ISSUE THREAD

**Issue by silentJET85** [TheAssassin/AppImageLauncher#410]
When trying to integrate a particular AppImage, I get the error "Failed to register AppImage in system via libappimage"

If I choose to Run once, the app seems to work fine.
So far, this is the only Appimage to have this problem; others have integrated without any problem.

The Appimage I tried:
https://www.fosshub.com/Avidemux.html?dwl=avidemuxLinux_2.7.8_GLIBC_2.28_amd64.appImage

My system:
Debian 11 Testing
Kernel 5.10.0-5-amd64
KDE Plasma 5.20.5

AppImageLauncher version: 2.2.0
Downloaded from: https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher_2.2.0-travis995.0f91801.bionic_amd64.deb

**Comment by DanielGlaas** [comment]
I have the same problem, exactly with the same Appimage of Avidemux!

I use Ubuntu 20.04 and installed AppImageLauncher via the PPA for Ubuntu.

**Comment by TheAssassin** [comment]
Broken AppImage:

```
[...]
appimagelint.cli[1265931] [INFO] Running check "Icons validity and location check"
appimagelint.icons_check[1265931] [INFO] Extracting icon name from desktop file: /tmp/.mount_avidemlEn5P5/avidemux.desktop
appimagelint.icons_check[1265931] [ERROR] Could not find Icon= entry in desktop file
appimagelint.icons_check[1265931] [INFO] [✖] Valid icon in AppDir root
appimagelint.icons_check[1265931] [INFO] Checking resolution of icon: /tmp/.mount_avidemlEn5P5/.DirIcon
[...]
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/.mount_avidemXXXXXX/.DirIcon'
```

Not a bug in AppImageLauncher.

**Comment by DanielGlaas** [comment]
> Broken AppImage:
> 
> ```
> [...]
> appimagelint.cli[1265931] [INFO] Running check "Icons validity and location check"
> appimagelint.icons_check[1265931] [INFO] Extracting icon name from desktop file: /tmp/.mount_avidemlEn5P5/avidemux.desktop
> appimagelint.icons_check[1265931] [ERROR] Could not find Icon= entry in desktop file
> appimagelint.icons_check[1265931] [INFO] [✖] Valid icon in AppDir root
> appimagelint.icons_check[1265931] [INFO] Checking resolution of icon: /tmp/.mount_avidemlEn5P5/.DirIcon
> [...]
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/.mount_avidemXXXXXX/.DirIcon'
> ```
> 
> Not a bug in AppImageLauncher. Please ask the authors of that AppImage to fix it. They may use appimagelint to check its validity.

Thank you very mich for your investigation! I will forward your results to the Team of Avidemux.

Nevertheless, what comes into my mind:
The error message of AppImageLauncher could be some kind of more detailed. Or maybe gives a hint how to generate your analysis such that a normal user has a better understanding why registration of the AppImage failed.

**Comment by DanielGlaas** [comment]
Just a hint for all Ubuntu and Debian users:
avidemux can be installed by a PPA: http://fixounet.free.fr/avidemux/download.html
I used this one for Ubuntu and with
`sudo add-apt-repository ppa:xtradeb/apps`
`sudo apt-get update`
`sudo apt install avidemux-qt`
avidemux is directly available from the App list and command line.

However: As this is my favourite way of installing this program, I will not continue with using it as an AppImage.

**Comment by TheAssassin** [comment]
I am working with what I get from libappimage. libappimage should probably get better at logging.

**Comment by Coll147** [comment]
Hi, I'm having the same error when integrating an appimage, but when I try to "run once" the application runs correctly.

**Comment by DeficientNull** [comment]
Same here, wanted to use the zen browser appimage but it doesn't seem to work and i don't feel like using flatpak.

**Comment by rooselle** [comment]
Hi, had the same problem with Nextcloud AppImage on Ubuntu 24 (Noble). "Run once" worked. Tried every solution I could find for the past hour (including deleting all Nextcloud-related files on the system) and none worked. In the end I uninstalled AppImageLauncher. Here's the result of appimagelint in case it can help (from what I understand the Nextcloud AppImage isn't broken):
```bash
./appimagelint-x86_64.AppImage ~/Applications/Nextcloud-3.15.0-x86_64.AppImage
appimagelint.cli[9915] [INFO] Checking AppImage /home/user/Applications/Nextcloud-3.15.0-x86_64.AppImage
appimagelint.cli[9915] [INFO] Running check "GNU libc ABI check"
appimagelint.glibc_abi_check[9915] [INFO] detected required version for runtime: 2.14
appimagelint.glibc_abi_check[9915] [INFO] detected required version for payload: 2.35
appimagelint.cache[9915] [INFO] Fetching glibc version data for debian
appimagelint.setup[9915] [INFO] Fetching glibc package versions from Debian sources API
appimagelint.glibc_abi_check[9915] [INFO] [✖] AppImage can run on Debian oldstable (bullseye)
appimagelint.glibc_abi_check[9915] [INFO] [✔] AppImage can run on Debian stable (bookworm)
appimagelint.glibc_abi_check[9915] [INFO] [✔] AppImage can run on Debian testing (trixie)
appimagelint.glibc_abi_check[9915] [INFO] [✔] AppImage can run on Debian unstable (sid)
appimagelint.cache[9915] [INFO] Fetching glibc version data for ubuntu
appimagelint.setup[9915] [INFO] Fetching glibc package versions from Ubuntu FTP mirror
appimagelint.glibc_abi_check[9915] [INFO] [✔] AppImage can run on Ubuntu oracular
appimagelint.glibc_abi_check[9915] [INFO] [✔] AppImage can run on Ubuntu noble
appimagelint.glibc_abi_check[9915] [INFO] [✔] AppImage can run on Ubuntu jammy
appimagelint.glibc_abi_check[9915] [INFO] [✖] AppImage can run on Ubuntu focal
appimagelint.glibc_abi_check[9915] [INFO] [✖] AppImage can run on Ubuntu bionic
appimagelint.glibc_abi_check[9915] [INFO] [✖] AppImage can run on Ubuntu xenial
appimagelint.glibc_abi_check[9915] [INFO] [✖] AppImage can run on Ubuntu trusty
appimagelint.cache[9915] [INFO] Fetching glibc version data for centos
appimagelint.setup[9915] [INFO] Fetching glibc package versions from CentOS mirror
appimagelint.cache[9915] [WARNING] codebase changed since last update, but updating failed, using cached data
appimagelint.cache[9915] [ERROR] 410 Client Error: Gone for url: https://ftp.fau.de/centos/7/os/x86_64/repodata//repomd.xml
Traceback (most recent call last):
  File "/tmp/.mount_appima1JSGar/usr/conda/lib/python3.9/site-packages/appimagelint/cache/json_cache_impl_base.py", line 101, in get_data
    new_data = cls._fetch_data()
  File "/tmp/.mount_appima1JSGar/usr/conda/lib/python3.9/site-packages/appimagelint/cache/package_version_maps.py", line 17, in _fetch_data
    return get_map_callback()
  File "/tmp/.mount_appima1JSGar/usr/conda/lib/python3.9/site-packages/appimagelint/cache/common.py", line 252, in get_centos_glibc_versions_map
    return get_centos_package_versions_map("glibc", r"libc\.so\.6\(GLIBC_(.*)\)")
  File "/tmp/.mount_appima1JSGar/usr/conda/lib/python3.9/site-packages/appimagelint/cache/common.py", line 151, in get_centos_package_versions_map
    primary_xml_root = ET.fromstring(get_centos_repodata_primary_xml(release))
  File "/tmp/.mount_appima1JSGar/usr/conda/lib/python3.9/site-packages/appimagelint/cache/common.py", line 126, in get_centos_repodata_primary_xml
    repomd_xml_root = ET.fromstring(get_request(f"{base_url}/repomd.xml").content)
  File "/tmp/.mount_appima1JSGar/usr/conda/lib/python3.9/site-packages/appimagelint/cache/common.py", line 119, in get_request
    response.raise_for_status()
  File "/tmp/.mount_appima1JSGar/usr/conda/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 410 Client Error: Gone for url: https://ftp.fau.de/centos/7/os/x86_64/repodata//repomd.xml
appimagelint.glibc_abi_check[9915] [INFO] [✖] AppImage can run on CentOS 7
appimagelint.cli[9915] [INFO] Running check "GNU libstdc++ ABI check"
appimagelint.glibcxx_abi_check[9915] [INFO] detected required version for runtime: <none>
appimagelint.glibcxx_abi_check[9915] [INFO] detected required version for payload: 3.4.30
appimagelint.cache[9915] [INFO] Fetching glibcxx version data for debian
appimagelint.gnu_lib_versions_symbols_finder[9915] [WARNING] no binaries found in /dev/shm/appimagelint-vfhgcl0t.tmp/out/
appimagelint.gnu_lib_versions_symbols_finder[9915] [WARNING] no binaries found in /dev/shm/appimagelint-u63neh6d.tmp/out/
appimagelint.gnu_lib_versions_symbols_finder[9915] [WARNING] no binaries found in /dev/shm/appimagelint-uwh2p8e7.tmp/out/
appimagelint.gnu_lib_versions_symbols_finder[9915] [WARNING] no binaries found in /dev/shm/appimagelint-xtt78dgk.tmp/out/
appimagelint.glibcxx_abi_check[9915] [INFO] [✖] AppImage can run on Debian oldstable (bullseye)
appimagelint.glibcxx_abi_check[9915] [INFO] [✖] AppImage can run on Debian stable (bookworm)
appimagelint.glibcxx_abi_check[9915] [INFO] [✖] AppImage can run on Debian testing (trixie)
appimagelint.glibcxx_abi_check[9915] [INFO] [✖] AppImage can run on Debian unstable (sid)
appimagelint.cache[9915] [INFO] Fetching glibcxx version data for ubuntu
appimagelint.gnu_lib_versions_symbols_finder[9915] [WARNING] no binaries found in /dev/shm/appimagelint-6uwcr9jt.tmp/out/
appimagelint.gnu_lib_versions_symbols_finder[9915] [WARNING] no binaries found in /dev/shm/appimagelint-vrbyklk8.tmp/out/
appimagelint.gnu_lib_versions_symbols_finder[9915] [WARNING] no binaries found in /dev/shm/appimagelint-89itaaj8.tmp/out/
appimagelint.gnu_lib_versions_symbols_finder[9915] [WARNING] no binaries found in /dev/shm/appimagelint-w5wclmkj.tmp/out/
appimagelint.gnu_lib_versions_symbols_finder[9915] [WARNING] no binaries found in /dev/shm/appimagelint-6eq5aad_.tmp/out/
appimagelint.gnu_lib_versions_symbols_finder[9915] [WARNING] no binaries found in /dev/shm/appimagelint-nfifh7gq.tmp/out/
appimagelint.gnu_lib_versions_symbols_finder[9915] [WARNING] no binaries found in /dev/shm/appimagelint-9xpp1wl7.tmp/out/
appimagelint.glibcxx_abi_check[9915] [INFO] [✔] AppImage can run on Ubuntu oracular
appimagelint.glibcxx_abi_check[9915] [INFO] [✔] AppImage can run on Ubuntu noble
appimagelint.glibcxx_abi_check[9915] [INFO] [✔] AppImage can run on Ubuntu jammy
appimagelint.glibcxx_abi_check[9915] [INFO] [✖] AppImage can run on Ubuntu focal
appimagelint.glibcxx_abi_check[9915] [INFO] [✖] AppImage can run on Ubuntu bionic
appimagelint.glibcxx_abi_check[9915] [INFO] [✖] AppImage can run on Ubuntu xenial
appimagelint.glibcxx_abi_check[9915] [INFO] [✖] AppImage can run on Ubuntu trusty
appimagelint.cache[9915] [INFO] Fetching glibcxx version data for centos
appimagelint.setup[9915] [INFO] Fetching libstdc++ package versions from CentOS mirror
appimagelint.cache[9915] [WARNING] codebase changed since last update, but updating failed, using cached data
appimagelint.cache[9915] [ERROR] 410 Client Error: Gone for url: https://ftp.fau.de/centos/7/os/x86_64/repodata//repomd.xml
Traceback (most recent call last):
  File "/tmp/.mount_appima1JSGar/usr/conda/lib/python3.9/site-packages/appimagelint/cache/json_cache_impl_base.py", line 101, in get_data
    new_data = cls._fetch_data()
  File "/tmp/.mount_appima1JSGar/usr/conda/lib/python3.9/site-packages/appimagelint/cache/package_version_maps.py", line 17, in _fetch_data
    return get_map_callback()
  File "/tmp/.mount_appima1JSGar/usr/conda/lib/python3.9/site-packages/appimagelint/cache/common.py", line 256, in get_centos_glibcxx_versions_map
    return get_centos_package_versions_map("libstdc++", r"libstdc\+\+\.so\.6\(GLIBCXX_(.*)\)")
  File "/tmp/.mount_appima1JSGar/usr/conda/lib/python3.9/site-packages/appimagelint/cache/common.py", line 151, in get_centos_package_versions_map
    primary_xml_root = ET.fromstring(get_centos_repodata_primary_xml(release))
  File "/tmp/.mount_appima1JSGar/usr/conda/lib/python3.9/site-packages/appimagelint/cache/common.py", line 126, in get_centos_repodata_primary_xml
    repomd_xml_root = ET.fromstring(get_request(f"{base_url}/repomd.xml").content)
  File "/tmp/.mount_appima1JSGar/usr/conda/lib/python3.9/site-packages/appimagelint/cache/common.py", line 119, in get_request
    response.raise_for_status()
  File "/tmp/.mount_appima1JSGar/usr/conda/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 410 Client Error: Gone for url: https://ftp.fau.de/centos/7/os/x86_64/repodata//repomd.xml
appimagelint.glibcxx_abi_check[9915] [INFO] [✖] AppImage can run on CentOS 7
appimagelint.cli[9915] [INFO] Running check "Icons validity and location check"
appimagelint.icons_check[9915] [INFO] Extracting icon name from desktop file: /tmp/.mount_Nextclu8JRce/com.nextcloud.desktopclient.nextcloud.desktop
appimagelint.icons_check[9915] [INFO] Checking resolution of icon: /tmp/.mount_Nextclu8JRce/Nextcloud.png
appimagelint.icons_check[9915] [INFO] [✔] Valid icon in AppDir root
appimagelint.icons_check[9915] [INFO] Checking resolution of icon: /tmp/.mount_Nextclu8JRce/.DirIcon
appimagelint.icons_check[9915] [INFO] [✔] Valid icon file in .DirIcon
appimagelint.icons_check[9915] [INFO] Checking resolution of icon: /tmp/.mount_Nextclu8JRce/usr/share/icons/hicolor/512x512/apps/Nextcloud.png
appimagelint.icons_check[9915] [INFO] [✔] Other integration icons valid
appimagelint.cli[9915] [INFO] Running check "Desktop files existence and validity"
appimagelint.desktop_files[9915] [INFO] Checking desktop files in root directory
appimagelint.desktop_files[9915] [INFO] [✔] Exactly one desktop file in AppDir root
appimagelint.desktop_files[9915] [INFO] Checking desktop file /tmp/.mount_Nextcl1sDEiq/com.nextcloud.desktopclient.nextcloud.desktop with desktop-file-validate
/tmp/.mount_Nextcl1sDEiq/com.nextcloud.desktopclient.nextcloud.desktop: warning: value "Nextcloud sincronizacion del client" for key "Comment[oc]" in group "Desktop Entry" looks the same as that of key "Name[oc]"
[...]
/tmp/.mount_Nextcl1sDEiq/usr/share/applications/com.nextcloud.desktopclient.nextcloud.desktop: warning: value "Nextcloud - Cliente de Sincronização para PC" for key "Comment[pt_PT]" in group "Desktop Entry" looks the same as that of key "Name[pt_PT]"
appimagelint.desktop_files[9915] [INFO] [✔] All desktop files in AppDir are valid
```

**Comment by ernstki** [comment]
**_tl;dr_: install [the latest release](https://github.com/TheAssassin/AppImageLauncher/releases)**

Here's another data point, from [the spotify-qt AppImage](https://github.com/kraxarn/spotify-qt/releases/tag/v4.0.1) that appears to pass the linter's checks without any serious problems:

<details>
    <summary>Output of <code>appimagelint</code></summary>

```console
$ appimagelint ~/opt/spotify-qt-v4.0.1_1131b7e943ecc6a343099607fa1702a8.AppImage 
appimagelint.cli[236752] [INFO] Checking AppImage /home/me/opt/spotify-qt-v4.0.1_1131b7e943ecc6a343099607fa1702a8.AppImage
appimagelint.cli[236752] [INFO] Running check "GNU libc ABI check"
appimagelint.glibc_abi_check[236752] [INFO] detected required version for runtime: <none>
appimagelint.glibc_abi_check[236752] [INFO] detected required version for payload: 2.34
appimagelint.glibc_abi_check[236752] [INFO] [✔] AppImage can run on Debian oldstable (bookworm)
appimagelint.glibc_abi_check[236752] [INFO] [✔] AppImage can run on Debian stable (trixie)
appimagelint.glibc_abi_check[236752] [INFO] [✔] AppImage can run on Debian testing (forky)
appimagelint.glibc_abi_check[236752] [INFO] [✔] AppImage can run on Debian unstable (sid)
appimagelint.glibc_abi_check[236752] [INFO] [✔] AppImage can run on Ubuntu plucky
appimagelint.glibc_abi_check[236752] [INFO] [✔] AppImage can run on Ubuntu noble
appimagelint.glibc_abi_check[236752] [INFO] [✔] AppImage can run on Ubuntu jammy
appimagelint.glibc_abi_check[236752] [INFO] [✖] AppImage can run on Ubuntu focal
appimagelint.glibc_abi_check[236752] [INFO] [✖] AppImage can run on Ubuntu bionic
appimagelint.glibc_abi_check[236752] [INFO] [✖] AppImage can run on Ubuntu xenial
appimagelint.glibc_abi_check[236752] [INFO] [✖] AppImage can run on Ubuntu trusty
appimagelint.glibc_abi_check[236752] [INFO] [✖] AppImage can run on Rocky Linux 8
appimagelint.glibc_abi_check[236752] [INFO] [✔] AppImage can run on Rocky Linux 9
appimagelint.cli[236752] [INFO] Running check "GNU libstdc++ ABI check"
appimagelint.glibcxx_abi_check[236752] [INFO] detected required version for runtime: <none>
appimagelint.glibcxx_abi_check[236752] [INFO] detected required version for payload: 3.4.29
appimagelint.glibcxx_abi_check[236752] [INFO] [✔] AppImage can run on Debian oldstable (bookworm)
appimagelint.glibcxx_abi_check[236752] [INFO] [✔] AppImage can run on Debian stable (trixie)
appimagelint.glibcxx_abi_check[236752] [INFO] [✔] AppImage can run on Debian testing (forky)
appimagelint.glibcxx_abi_check[236752] [INFO] [✔] AppImage can run on Debian unstable (sid)
appimagelint.glibcxx_abi_check[236752] [INFO] [✔] AppImage can run on Ubuntu plucky
appimagelint.glibcxx_abi_check[236752] [INFO] [✔] AppImage can run on Ubuntu noble
appimagelint.glibcxx_abi_check[236752] [INFO] [✔] AppImage can run on Ubuntu jammy
appimagelint.glibcxx_abi_check[236752] [INFO] [✖] AppImage can run on Ubuntu focal
appimagelint.glibcxx_abi_check[236752] [INFO] [✖] AppImage can run on Ubuntu bionic
appimagelint.glibcxx_abi_check[236752] [INFO] [✖] AppImage can run on Ubuntu xenial
appimagelint.glibcxx_abi_check[236752] [INFO] [✖] AppImage can run on Ubuntu trusty
appimagelint.glibcxx_abi_check[236752] [INFO] [✖] AppImage can run on Rocky Linux 8
appimagelint.glibcxx_abi_check[236752] [INFO] [✔] AppImage can run on Rocky Linux 9
appimagelint.cli[236752] [INFO] Running check "Icons validity and location check"
appimagelint.icons_check[236752] [INFO] Extracting icon name from desktop file: /tmp/.mount_runtimOjfKlJ/spotify-qt.desktop
appimagelint.icons_check[236752] [INFO] Checking resolution of icon: /tmp/.mount_runtimOjfKlJ/spotify-qt.svg
appimagelint.icons_check[236752] [INFO] [✔] Valid icon in AppDir root
appimagelint.icons_check[236752] [INFO] Checking resolution of icon: /tmp/.mount_runtimOjfKlJ/.DirIcon
appimagelint.icons_check[236752] [INFO] [✔] Valid icon file in .DirIcon
appimagelint.icons_check[236752] [INFO] Checking resolution of icon: /tmp/.mount_runtimOjfKlJ/usr/share/icons/hicolor/scalable/apps/spotify-qt.svg
appimagelint.icons_check[236752] [INFO] [✔] Other integration icons valid
appimagelint.cli[236752] [INFO] Running check "Desktop files existence and validity"
appimagelint.desktop_files[236752] [INFO] Checking desktop files in root directory
appimagelint.desktop_files[236752] [INFO] [✔] Exactly one desktop file in AppDir root
appimagelint.desktop_files[236752] [INFO] Checking desktop file /tmp/.mount_runtimiCLiLe/spotify-qt.desktop with desktop-file-validate
appimagelint.desktop_files[236752] [INFO] Checking desktop file /tmp/.mount_runtimiCLiLe/usr/share/applications/spotify-qt.desktop with desktop-file-validate
appimagelint.desktop_files[236752] [INFO] [✔] All desktop files in AppDir are valid
```
</details>

<details>
    <summary>Command-line output</summary>

```console
$ ~/opt/spotify-qt-v4.0.1_1131b7e943ecc6a343099607fa1702a8.AppImage 
Squashfs image uses (null) compression, this version supports only xz, zlib.
ERROR: appimage_shall_not_be_integrated : sqfs_open_image error: /home/me/opt/spotify-qt-v4.0.1_1131b7e943ecc6a343099607fa1702a8.AppImage
AppImageLauncher error: appimage_shall_not_be_integrated() failed (returned -1)
Squashfs image uses (null) compression, this version supports only xz, zlib.
ERROR: appimage_is_terminal_app : sqfs_open_image error: /home/me/opt/spotify-qt-v4.0.1_1131b7e943ecc6a343099607fa1702a8.AppImage
AppImageLauncher error: appimage_is_terminal_app() failed (returned -1)
fuse: memory allocation failed
squashfuse 0.5.2 (c) 2012 Dave Vasilevsky

Usage: squashfuse [options] ARCHIVE MOUNTPOINT

(null) options:
    -o offset=N            offset N bytes into ARCHIVE to mount
    -o subdir=PATH         mount subdirectory PATH of ARCHIVE
    -o notify_pipe=PATH    named pipe that will receive 's' (success)
                           or 'f' (failure) when the mountpoint is ready
    -o timeout=N           idle N seconds for automatic unmount
    -o uid=N               set file owner to uid N
    -o gid=N               set file group to gid N

FUSE options:
    -h   --help            print help
    -V   --version         print version
    -d   -o debug          enable debug output (implies -f)
    -f                     foreground operation
    -s                     disable multi-threaded operation
    -o clone_fd            use separate fuse device fd for each thread
                           (may improve performance)
    -o max_idle_threads    the maximum number of idle worker threads
                           allowed (default: -1)
    -o max_threads         the maximum number of worker threads
                           allowed (default: 10)
fuse: memory allocation failed
squashfuse 0.5.2 (c) 2012 Dave Vasilevsky

Usage: squashfuse [options] ARCHIVE MOUNTPOINT

(null) options:
    -o offset=N            offset N bytes into ARCHIVE to mount
    -
```
</details>

Two important looking error messages from the command-line output are

    Squashfs image uses (null) compression, this version supports only xz, zlib.

and

    fuse: memory allocation failed


Searching for the first error message led me to https://github.com/TheAssassin/AppImageLauncher/issues/657, wherein I found [the suggestion](https://github.com/TheAssassin/AppImageLauncher/issues/657#issuecomment-2336780292) to use the latest continuous build. **Which did in fact work in this particular case**, so that's probably what you should try if you get this issue.

It wasn't clear to me that I shouldn't use the `bionic` package, though (noting the instructions [here](https://github.com/TheAssassin/AppImageLauncher?tab=readme-ov-file#system-wide-installation)), and I'm generally timid about "alpha" releases. So I'm leaving this breadcrumb trail here for others who find themselves in a similar situation.

**Comment by rk9qn3j** [comment]
Installing 3.0.0 beta 3 solved this for me.
