### ISSUE TITLE
Ubuntu 20.04 Repo - installs fine but "doesn't work"

### ISSUE THREAD

**Issue by mangelozzi** [TheAssassin/AppImageLauncher#466]
Same issue as #327 

Describe the bug

As in title. I've installed focal and the first thing I installed after fresh OS install was Appimagelauncher from the official repo in the wiki here. And did a reboot after install.

I've checked apt settings and the repo is correctly set as the Ubuntu focal PPA repo. Exactly installed as per the Wiki instructions here.

When I double click on any of my appimages it does nothing at all. No errors but no actions. And app doesn't run. There is nothing after double clicking.

Expected behavior

It asks me if I want to run or run and integrate as usual.

I added my app dir:
![image](https://user-images.githubusercontent.com/19764314/146947989-b918f7f9-f17a-4299-9648-81ef6fad0abb.png)

## Installed via

```
sudo add-apt-repository ppa:appimagelauncher-team/stable
sudo apt install appimagelauncher
sudo apt install appimagelauncher
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  binfmt-support libappimage0 libsquashfuse0
The following NEW packages will be installed:
  appimagelauncher binfmt-support libappimage0 libsquashfuse0
0 upgraded, 4 newly installed, 0 to remove and 172 not upgraded.
Need to get 364 kB of archives.
After this operation, 1,694 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://za.archive.ubuntu.com/ubuntu focal/universe amd64 binfmt-support amd64 2.2.0-2 [58.2 kB]   
Get:2 http://za.archive.ubuntu.com/ubuntu focal/universe amd64 libsquashfuse0 amd64 0.1.103-2 [24.5 kB] 
Get:3 http://za.archive.ubuntu.com/ubuntu focal/universe amd64 libappimage0 amd64 0.1.9+dfsg-1 [24.5 kB]
Get:4 http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu focal/main amd64 appimagelauncher amd64 202110042218-stable-0f91801~ubuntu20.04.1 [257 kB]
Fetched 364 kB in 11s (32.3 kB/s)                                              
Selecting previously unselected package binfmt-support.
(Reading database ... 191391 files and directories currently installed.)
Preparing to unpack .../binfmt-support_2.2.0-2_amd64.deb ...
Unpacking binfmt-support (2.2.0-2) ...
Selecting previously unselected package libsquashfuse0:amd64.
Preparing to unpack .../libsquashfuse0_0.1.103-2_amd64.deb ...
Unpacking libsquashfuse0:amd64 (0.1.103-2) ...
Selecting previously unselected package libappimage0:amd64.
Preparing to unpack .../libappimage0_0.1.9+dfsg-1_amd64.deb ...
Unpacking libappimage0:amd64 (0.1.9+dfsg-1) ...
Setting up binfmt-support (2.2.0-2) ...
Created symlink /etc/systemd/system/multi-user.target.wants/binfmt-support.service → /lib/systemd/system/binfmt-support.service.
Selecting previously unselected package appimagelauncher.
(Reading database ... 191418 files and directories currently installed.)
Preparing to unpack .../appimagelauncher_202110042218-stable-0f91801~ubuntu20.04.1_amd64.deb ...
Unpacking appimagelauncher (202110042218-stable-0f91801~ubuntu20.04.1) ...
Setting up libsquashfuse0:amd64 (0.1.103-2) ...
Setting up libappimage0:amd64 (0.1.9+dfsg-1) ...
Setting up appimagelauncher (202110042218-stable-0f91801~ubuntu20.04.1) ...
Installing AppImageLauncher as interpreter for AppImages
+ update-binfmts --package appimage --install appimage-type1 /usr/bin/AppImageLauncher --magic 'AI\x01' --offset 8
+ update-binfmts --package appimage --install appimage-type2 /usr/bin/AppImageLauncher --magic 'AI\x02' --offset 8
Created symlink /etc/systemd/user/default.target.wants/appimagelauncherd.service → /usr/lib/systemd/user/appimagelauncherd.service.
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for shared-mime-info (1.15-1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Processing triggers for systemd (245.4-4ubuntu3.11) ...
```

PErforming the requesting suggestion (results in the app starting as usual like when applauncher was not installed, no applauncher dialogue).
_Originally posted by @TheAssassin in https://github.com/TheAssassin/AppImageLauncher/issues/327#issuecomment-620868400_
If you don't mind, you could try to call AppImageLauncher directly on an AppImage and see what that does. `AppImageLauncher my.non-integrated.AppImage`. It might be the `binfmt_misc` or MIME integration that broke on your system.

```
AppImageLauncher ~/appimages/cryptomator-1.6.5-x86_64.AppImage 
/usr/bin/dpkg
16:37:11.242 [main] DEBUG org.cryptomator.common.Environment - user.home: /home/michael
16:37:11.245 [main] DEBUG org.cryptomator.common.Environment - java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
16:37:11.245 [main] DEBUG org.cryptomator.common.Environment - user.language: en
16:37:11.245 [main] DEBUG org.cryptomator.common.Environment - user.region: null
16:37:11.245 [main] DEBUG org.cryptomator.common.Environment - logback.configurationFile: null
16:37:11.245 [main] DEBUG org.cryptomator.common.Environment - cryptomator.settingsPath: ~/.config/Cryptomator/settings.json:~/.Cryptomator/settings.json
16:37:11.245 [main] DEBUG org.cryptomator.common.Environment - cryptomator.ipcSocketPath: ~/.config/Cryptomator/ipc.socket
16:37:11.245 [main] DEBUG org.cryptomator.common.Environment - cryptomator.keychainPath: null
16:37:11.245 [main] DEBUG org.cryptomator.common.Environment - cryptomator.logDir: ~/.local/share/Cryptomator/logs
16:37:11.245 [main] DEBUG org.cryptomator.common.Environment - cryptomator.pluginDir: ~/.local/share/Cryptomator/plugins
16:37:11.245 [main] DEBUG org.cryptomator.common.Environment - cryptomator.mountPointsDir: ~/.local/share/Cryptomator/mnt
16:37:11.245 [main] DEBUG org.cryptomator.common.Environment - cryptomator.minPwLength: null
16:37:11.245 [main] DEBUG org.cryptomator.common.Environment - cryptomator.appVersion: 1.6.5
16:37:11.245 [main] DEBUG org.cryptomator.common.Environment - cryptomator.buildNumber: appimage-3397
16:37:11.245 [main] DEBUG org.cryptomator.common.Environment - cryptomator.showTrayIcon: null
16:37:11.245 [main] DEBUG org.cryptomator.common.Environment - fuse.experimental: false
16:37:11.271 [main] DEBUG org.cryptomator.common.ShutdownHook - Registered shutdown hook.
16:37:11.361 [main] DEBUG org.cryptomator.common.settings.SettingsProvider - Attempting to load settings from /home/michael/.config/Cryptomator/settings.json
16:37:11.432 [main] INFO org.cryptomator.common.settings.SettingsProvider - Settings loaded from /home/michael/.config/Cryptomator/settings.json
16:37:11.435 [main] INFO  org.cryptomator.launcher.Cryptomator - Starting Cryptomator 1.6.5 on Linux 5.11.0-43-generic (amd64)
16:37:11.458 [main] INFO  org.cryptomator.ipc.Server - Spawning IPC server listening on socket /home/michael/.config/Cryptomator/ipc.socket
16:37:12.082 [JavaFX Application Thread] INFO  o.c.ui.launcher.FxApplicationStarter - JavaFX Runtime started.
16:38:52.858 [main] INFO  org.cryptomator.launcher.Cryptomator - UI shut down
16:38:52.859 [main] INFO  org.cryptomator.launcher.Cryptomator - Exit 0
Exception in thread "DBusConnection" java.util.concurrent.RejectedExecutionException: Task org.freedesktop.dbus.connections.AbstractConnection$1@52e96fbc rejected from java.util.concurrent.ThreadPoolExecutor@7245aed4[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 14]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at org.freedesktop.dbus.connections.AbstractConnection.sendMessage(AbstractConnection.java:385)
	at org.freedesktop.dbus.connections.AbstractConnection.handleMessage(AbstractConnection.java:1061)
	at org.freedesktop.dbus.connections.AbstractConnection.handleMessage(AbstractConnection.java:720)
	at org.freedesktop.dbus.connections.IncomingMessageThread.run(IncomingMessageThread.java:43)
```

**Comment by Tommy-01** [comment]
I'm on Linux Mint 20.3 and got the same problem.
Is there any Information needed to solve this?
Maybe i can help.

**Comment by TheAssassin** [comment]
Does that affect all AppImages or just Cryptomator? The latter is known for being somewhat broken...

**Comment by Tommy-01** [comment]
For me it affect all AppImages i use.

- LibreWolf.x86_64
- Nextcloud
- Joplin

**Comment by Tommy-01** [comment]
I still get the red "Updater available" as you can see in the first Screenshot.
But i get the AppImageLauncher to register my new, self downloaded, .appimage Files.
I have do start the new Files outside the registered default location. Then AppImageLauncher start and register the new file as expected. And also it moves the new File to the registered default location.

**Comment by TheAssassin** [comment]
> I still get the red "Updater available" as you can see in the first Screenshot.

That's normal. The PPA does not provide all features. Until libappimageupdate is available from Ubuntu, this is to be expected.

**Comment by Tommy-01** [comment]
Ok, thank you!
